Login screen
Katios-C/MissingPet pull request #1
Opened 2022-06-15 03:35 UTC by Katios-C

2022-06-15 04:09 UTC, Nikolaiko requested changes
Фалов шрифтов не хватает, проект не собирается.

2022-06-15 05:12 UTC, Katios-C commented
> Фалов шрифтов не хватает, проект не собирается.
добавила

2022-06-15 07:37 UTC, Nikolaiko requested changes
Шрифт MulishRegular по прежнему есть в списке файлов, но его нет в проекте. Приходится его удалять руками из списка файлов проекта. Исправь это, удали его из списка файлов проекта и закомить.

2022-06-15 07:37 UTC, Nikolaiko commented on Views/Login/LoginView.swift
> +                .padding(.bottom, UIScreen.main.bounds.size.width / 18)
Нужно оборачивать всю вьюху GeometryReader и оттуда брать максимальные значения. Использовать UIScreen - не правильно.

2022-06-15 07:37 UTC, Nikolaiko commented on Views/Login/LoginWindowView.swift
> +            Image(fullButtonTitle)
Здесь нужно сделать кнопку с картинкой и текстом отдельно. А не все картинкой.

2022-06-15 07:37 UTC, Nikolaiko commented on Views/Login/TextFieldLogin.swift
> +struct TextFieldLogin: View {
Вынести в отдельную View хорошее решение.

2022-06-15 10:49 UTC, Katios-C commented
> Шрифт MulishRegular по прежнему есть в списке файлов, но его нет в проекте. Приходится его удалять руками из списка файлов проекта. Исправь это, удали его из списка файлов проекта и закомить.

Я подправила и оставила три шрифта, она все используются в проекте, потому что тот, что ты скинул в трепло, не работает с русскими буквами.

2022-06-15 10:49 UTC, Katios-C commented on Views/Login/LoginView.swift
> +                .padding(.bottom, UIScreen.main.bounds.size.width / 18)
+

2022-06-15 10:50 UTC, Katios-C commented on Views/Login/LoginWindowView.swift
> +            Image(fullButtonTitle)
+

2022-06-16 04:55 UTC, Nikolaiko approved these changes

2022-06-17 01:06 UTC, merged